spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_keep?serverTimezone=GMT%2B8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:templates/,classpath:static/

server:
  port: 8090
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.keep.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.keep.mapper: debug